spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://localhost:3306/booking_service
    username: tahabens
    password: taassbewell
    driver-class-name: com.mysql.cj.jdbc.Driver


  sql:
    init:
      mode: always

  session:
    jdbc:
      initialize-schema: always
    # store-type: jdbc

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

app:
  rabbitmq:
    exchange: ${APP_RABBITMQ_EXCHANGE:bewell.exchange}
    queue:
      booking-created-queue: ${APP_RABBITMQ_QUEUE_BOOKING_CREATED:booking.booking-created}
    routingkey:
      booking-created: ${APP_RABBITMQ_ROUTINGKEY_BOOKING_CREATED:rk.booking.booking-created}

services:
  salon:
    url: ${SERVICES_SALON_URL:http://salon-service:8085}
  client:
    url: ${SERVICES_CLIENT_URL:http://client-service:8088}

server:
  port: 8086
