spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/client_service
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  session:
    jdbc:
      initialize-schema: always

server:
  port: 8088

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE