server:
  port: 8083

spring:
  application:
    name: notification-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  # JavaMail
  mail:
    host: smtp.gmail.com
    port: 587
    username: bewell.notification00@gmail.com
    password: ulilczcplrfzphwc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # RabbitMQ
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:user}
    password: ${SPRING_RABBITMQ_PASSWORD:password}

app:
  rabbitmq:
    exchange: ${APP_RABBITMQ_EXCHANGE:bewell.exchange}
    queue:
      booking-created-queue: ${APP_RABBITMQ_QUEUE_BOOKING_CREATED:booking.booking-created}
    routingkey:
      booking-created: ${APP_RABBITMQ_ROUTINGKEY_BOOKING_CREATED:rk.booking.booking-created}