server:
  port: 8093

spring:
  application:
    name: notification-service

  # JavaMail
  mail:
    host: smtp.gmail.com
    port: 587
    username: bewell.notification00@gmail.com
    password: ulilczcplrfzphwc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbitmq:
    exchange: bewell.exchange
    queue:
      booking-created-queue: booking.booking-created
    routingkey:
      booking-created: rk.booking.booking-created