services:

  # API Gateway
  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - review-service
      - user-service
      - booking-service
      - salon-service
      - auth-service


  # MySQL Database
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  # Auth Service
  auth-service:
    build: ./backend/auth-service
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auth_service
      SPRING_DATASOURCE_USERNAME: ${APP_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${APP_DB_PASSWORD}

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5432:5432"
      - "15672:15672"

  # User Service
  user-service:
    build: ./backend/user-service
    depends_on:
      - mysql
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/client_service
      SPRING_DATASOURCE_USERNAME: tahabens
      SPRING_DATASOURCE_PASSWORD: taassbewell

  # Booking Service
  booking-service:
    build: ./backend/booking-service
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/booking_service
      SPRING_DATASOURCE_USERNAME: tahabens
      SPRING_DATASOURCE_PASSWORD: taassbewell
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password
      APP_RABBITMQ_EXCHANGE: bewell-exchange
      APP_RABBITMQ_QUEUE_BOOKING_CREATED: bewell-queue
      APP_RABBITMQ_ROUTINGKEY_BOOKING_CREATED: rk.booking.booking-created

#  # Payment Service
#  payment-service:
#    build: ./backend/payment-service
#    depends_on:
#      - mysql
#    ports:
#      - "8087:8087"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payment_service
#      SPRING_DATASOURCE_USERNAME: ${APP_DB_USER}
#      SPRING_DATASOURCE_PASSWORD: ${APP_DB_PASSWORD}

  # Review Service
  review-service:
    build: ./backend/review-service
    environment:
      - SPRING_DATA_MONGODB_URI
    ports:
      - "8084:8084"

  # Salon Service
  salon-service:
    build: ./backend/salon-service
    environment:
      - SPRING_NEO4J_URI
      - SPRING_NEO4J_AUTHENTICATION_USERNAME
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD
      - SPRING_AI_OPENAI_API_KEY
    ports:
      - "8085:8085"

  # Notification Service
  notification-service:
    build: ./backend/notification-service
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password
      APP_RABBITMQ_EXCHANGE: bewell-exchange
      APP_RABBITMQ_QUEUE_BOOKING_CREATED: bewell-queue
      APP_RABBITMQ_ROUTINGKEY_BOOKING_CREATED: rk.booking.booking-created
    ports:
      - "8086:8086"
#
#  # Frontend
#  frontend:
#    build: ./frontend/react-app
#    ports:
#      - "3000:80"

volumes:
  mysql_data:
  rabbitmq_data:
