services:

  # API Gateway
  api-gateway:
    container_name: api-gateway
    build: ./backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - review-service
      - user-service
      - booking-service
      - salon-service


  # MySQL Database
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  # User Service
  user-service:
    build: ./backend/user-service
    container_name: bewell-user-service
    depends_on:
      - mysql
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/client_service
      SPRING_DATASOURCE_USERNAME: ${APP_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${APP_DB_PASSWORD}

  # Booking Service
  booking-service:
    build: ./backend/booking-service
    container_name: bewell-booking-service
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/booking_service
      SPRING_DATASOURCE_USERNAME: ${APP_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${APP_DB_PASSWORD}

  # Payment Service
  payment-service:
    build: ./backend/payment-service
    depends_on:
      - mysql
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payment_service
      SPRING_DATASOURCE_USERNAME: ${APP_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${APP_DB_PASSWORD}

  # Review Service
  review-service:
    build: ./backend/review-service
    container_name: bewell-review-service
    environment:
      - SPRING_DATA_MONGODB_URI
    ports:
      - "8084:8084"

  # Salon Service
  salon-service:
    build: ./backend/salon-service
    container_name: bewell-salon-service
    environment:
      - SPRING_NEO4J_URI
      - SPRING_NEO4J_AUTHENTICATION_USERNAME
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD
      - SPRING_AI_OPENAI_API_KEY
    ports:
      - "8085:8085"

  # Notification Service
  notification-service:
    build: ./backend/notification-service
    ports:
      - "8086:8080"

  # Frontend
  frontend:
    build: ./frontend/react-app
    ports:
      - "3000:80"

volumes:
  mysql_data: