spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/auth_service}
    username: ${SPRING_DATASOURCE_USERNAME:tahabens}
    password: ${SPRING_DATASOURCE_PASSWORD:taassbewell}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
  session:
    jdbc:
      initialize-schema: always

server:
  port: 8081

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

jwt:
  secret: "thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd"
  expiration: 3600000