export * from "./home_page"
export * from "./salons";
export * from "./review";
export * from "./reviews";
export * from "./not_found";
export * from "./create_reservation";
export * from "./authentication";
export * from "./payment_success_page";
export * from "./payment_cancel_page";
