apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: bewell
  labels:
    app: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: bewell/review-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085