apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: bewell
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081