apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: bewell
spec:
  type: ClusterIP
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082