apiVersion: v1
kind: Service
metadata:
  name: message-common
  namespace: bewell
spec:
  type: ClusterIP
  selector:
    app: message-common
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095