apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: bewell
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087