apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: bewell
spec:
  type: ClusterIP
  selector:
    app: review-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084