apiVersion: v1
kind: Service
metadata:
  name: salon-service
  namespace: bewell
spec:
  type: ClusterIP
  selector:
    app: salon-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085