apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: bewell
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088